ci(backoffice-bff): finish

diff --git a/.github/workflows/backoffice-bff-ci.yaml b/.github/workflows/backoffice-bff-ci.yaml
--- a/.github/workflows/backoffice-bff-ci.yaml
+++ b/.github/workflows/backoffice-bff-ci.yaml
@@ -1,4 +1,3 @@
-# test commit
 name: backoffice-bff service ci
 
 on:
@@ -30,10 +29,10 @@ jobs:
       FROM_ORIGINAL_REPOSITORY: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository }}
       RUN_SECURITY_SCANS: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository }}
     steps:
-      - name: Force CI failure (test)
-        run: |
-          echo "Intentional failure for CI test"
-          exit 1
+      # - name: Force CI failure (test)
+      #   run: |
+      #     echo "Intentional failure for CI test"
+      #     exit 1
       - uses: actions/checkout@v4
         with:
           fetch-depth: 0
